output "namespace" {
  value = var.namespace
}

output "elasticsearch_service" {
  value = "https://${local.es_http_host}:9200"
}

output "kibana_service" {
  value = var.enable_kibana_route ? "http://kibana-kb-http.${var.namespace}.svc:5601" : "https://kibana-kb-http.${var.namespace}.svc:5601"
}

output "kibana_url" {
  description = "How to reach Kibana"
  value       = var.enable_kibana_route ? "https://${var.kibana_hostname}" : "not exposed — use port-forward"
}

output "get_elastic_password" {
  description = "Retrieve the 'elastic' superuser password generated by ECK"
  value       = <<-EOT
    kubectl get secret elasticsearch-es-elastic-user -n ${var.namespace} \
      -o jsonpath='{.data.elastic}' | base64 -d
  EOT
}

output "elastic_password" {
  description = "The 'elastic' superuser's current password — read directly from the cluster. Either ECK's auto-generated value, or whatever custom_elastic_password was last set to."
  # The kubernetes provider marks kubernetes_secret's `data` attribute
  # sensitive at the schema level regardless of our own config, so this
  # output has to explicitly opt back out with nonsensitive() to actually
  # display the value instead of erroring or redacting it.
  value = nonsensitive(data.kubernetes_secret.elastic_password.data["elastic"])
}

output "port_forward_kibana" {
  description = "Access Kibana locally without the gateway (user: elastic)"
  value       = "kubectl port-forward -n ${var.namespace} service/kibana-kb-http 5601"
}

output "check_status" {
  value = "kubectl get elasticsearch,kibana,agent -n ${var.namespace}"
}
